export enum PropertyZone {
  INSIDE_SIR = 'INSIDE_SIR',
  OUTSIDE_SIR = 'OUTSIDE_SIR',
}

export enum PropertyType {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  AGRICULTURAL = 'AGRICULTURAL',
  LAND_PLOT = 'LAND_PLOT',
}

export enum PropertyStatus {
  AVAILABLE = 'AVAILABLE',
  UNDER_NEGOTIATION = 'UNDER_NEGOTIATION',
  SOLD = 'SOLD',
  RESERVED = 'RESERVED',
}